name=input("Enter your full Name: ")
age=int(input("Enter your age: "))
email=input("Enter your Email address: ")
p=int(input("Enter your phone number: "))
print("----User Information Input----")
print("Name:",name)
print("Age:",age)
print("Email:",email)
print("Phone Number:",p)